version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_HOST: localhost
      POSTGRES_SSLMODE: disable
    # volumes:
    #   - 
    
  redis:
    image: redis
    container_name: redis 
    command: redis-server --requirepass qwerty
    ports:
     - 6380:6379
    # volumes:
    #   - redis_data:/data
    # command: redis-server --appendonly yes

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: qwertyqwerty
    # volumes:
    #   - minio_data:/data
    command: server /data --console-address ":9000"

  # backend:
    # image:
    # ports:
    #  - "8080:8080"
    # environment:
    #   POSTGRES_DB: postgres
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: qwerty
    #   POSTGRES_HOST: localhost
    #   POSTGRES_SSLMODE: disable
    # volumes:
    #   - data/




      
