version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_HOST: localhost
      POSTGRES_SSLMODE: disable
    
  # redis:
  #   image: redis
  #   ports:
  #    - 0:0

  # backend:
  #   image:
  #   ports:
  #    -0:0
  #   environment:
      
